name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
       
      - name: Test
        run: go test -timeout 300s -run ^TestUserMysqlRepo repos/repositories