name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Install
        run: |
          go mod download
          go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
       
      - name: Test
        run: |
          go test -coverprofile=./cover.out -covermode=atomic -json -run ^TestUser repos/repositories | go-ctrf-json-reporter -output ctrf-report.json
          go tool cover -html=cover.out -o=cover.html

      - name: Publish CTRF Test Summary Results
        run: npx github-actions-ctrf ctrf-report.json
        if: always()

      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'cover.html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1