name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Install
        run: |
          go mod download
          go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
       
      - name: Test
        run: go test -cover -coverprofile=coverage.txt -json -run ^TestUser repos/repositories | go-ctrf-json-reporter -output ctrf-report.json

      - name: Publish CTRF Test Summary Results
        run: npx github-actions-ctrf ctrf-report.json
        if: always()

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.txt
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
  
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md