name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Install
        run: go mod download
       
      - name: Test
        run: go test -run ^TestUserMysqlRepo repos/repositories